---
- name: Create crawl db and gamedirs
  command: "{{ crawl_dev_dir }}dgamelaunch-config/bin/dgl {{ item.command }}"
  args:
    creates: "{{ item.creates }}"
  with_items:
    - command: create-versions-db
      creates: "{{ chroot_dir }}crawl-versions.db3"
    - command: create-crawl-gamedir
      creates: "{{ chroot_dir }}crawl-master/crawl-git/saves/logfile"

- name: Create versions from git
  command: cp -a {{ chroot_dir }}crawl-master/crawl-git {{ chroot_dir }}crawl-master/crawl-{{ item }}
  args:
    creates: "{{ chroot_dir }}crawl-master/crawl-{{ item }}/saves/logfile"
  with_items: "{{ versions | union(experimentals) }}"

- name: Push configs to chroot and /etc
  command: "{{ crawl_dev_dir }}dgamelaunch-config/bin/dgl publish --confirm"

- name: Ensure locale is correctly installed
  locale_gen: name=en_US.UTF-8 state=present

- block:
  - name: Installing versions ( this will take a long while... )
    command: "{{ crawl_dev_dir }}dgamelaunch-config/bin/dgl update-stable {{ item }}"
    args:
      creates: "{{ chroot_dir }}crawl-master/crawl-{{ item }}/data/docs/changelog.txt"
    with_items: "{{ versions }}"

  - name: Installing trunk ( go grab a coffee... )
    command: "{{ crawl_dev_dir }}dgamelaunch-config/bin/dgl update-trunk"
    args:
      creates: "{{ chroot_dir }}crawl-master/crawl-latest/data/docs/changelog.txt"
  become_user: crawl-dev
  become: yes

- name: Copy webserver templates to correct locations
  shell: cp {{ crawl_dev_dir }}dgamelaunch-config/crawl-build/crawl-git-repository/crawl-ref/source/webserver/templates/*.html {{ chroot_dir }}crawl-master/webserver/templates/
  args:
    creates: "{{ chroot_dir }}crawl-master/webserver/templates/client.html"

- name: Installing experimentals ( might as well take a walk outside... )
  shell: "{{ crawl_dev_dir }}dgamelaunch-config/bin/dgl update-stable {{ item }}"
  args:
    creates: "{{ chroot_dir }}crawl-master/crawl-{{ item }}/data/docs/changelog.txt"
  with_items: "{{ experimentals }}"
  become_user: crawl-dev
  become: yes

- name: Ensure wwwdir exists
  file:
    path: /var/www/crawl
    state: directory

- name: Symlink folders to wwwdir
  file:
    src: "{{ chroot_dir }}dgldir/{{ item }}"
    dest: /var/www/crawl/{{ item }}
    state: link
  with_items:
    - morgue
    - rcfiles
    - ttyrec

- block:
  - name: Git clone tornado
    git:
      repo: git://github.com/flodiebold/tornado.git
      dest: "{{ crawl_dev_dir }}tornado"
      version: http-timeouts-2.4

  - name: Build tornado
    command: python setup.py build
    args:
      chdir: "{{ crawl_dev_dir }}tornado"
      creates: "{{ crawl_dev_dir }}tornado/build/lib.linux-x86_64-2.7/tornado/__init__.py"
  become_user: crawl-dev
  become: yes

- name: Ensure permissions are correct
  command: chown -R crawl:crawl {{ chroot_dir }}{{ item }}
  changed_when: false
  with_items:
    - crawl-master/
    - dgldir/
